[package]
name = "CGRA-Mapper-Rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "EggLib"
crate-type = ["dylib"]

[dependencies]
#egg = "0.7.1"
egg = { git = "https://github.com/egraphs-good/egg", rev = "269c78636f91674da8c38838410d6fbdea08e099", features = ["lp"] }
libc = "0.2"